[package]
name = "css_parser"
version = "0.1.0"
authors = ["oleg.a.dovger <oleg.a.dovger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
